# Generated by Django 5.1.2 on 2024-10-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_recipepostmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofilemodel',
            name='Image',
            field=models.ImageField(null=True, upload_to='Media/Blog_Pic'),
        ),
        migrations.AddField(
            model_name='viewersprofilemodel',
            name='Image',
            field=models.ImageField(null=True, upload_to='Media/Blog_Pic'),
        ),
    ]
