# Generated by Django 5.1.2 on 2024-10-20 23:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_creatorprofilemodel_image_viewersprofilemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepostmodel',
            name='CookingTime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='recipepostmodel',
            name='PreparetionTime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='recipepostmodel',
            name='TotalTime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
