# Generated by Django 5.1.2 on 2024-10-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_recipepostmodel_cookingtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='Display_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='user_type',
            field=models.CharField(choices=[('recruiters', 'Recruiters'), ('jobseeker', 'Jobseeker')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='RecipePostModel',
        ),
    ]
