# Generated by Django 5.1.2 on 2024-10-22 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_custom_user_display_name_alter_custom_user_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255, null=True)),
                ('Number_of_opening', models.PositiveIntegerField(null=True)),
                ('Category', models.CharField(choices=[('fulltime', 'Full-time'), ('parttime', 'Part-time')], max_length=255, null=True)),
                ('Job_Description', models.TextField(max_length=255, null=True)),
                ('Skills', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
