# Generated by Django 5.1.2 on 2024-10-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_jobmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='company_logo',
            field=models.ImageField(null=True, upload_to='Media/Blog_Pic'),
        ),
    ]
