# Generated by Django 5.1.2 on 2024-10-22 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_intermediate_skillmodel_skills_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofilemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creatorsProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
