# Generated by Django 5.1 on 2024-10-22 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_creatorprofilemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjobmodel',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='applyjobmodel',
            name='Job_Description',
        ),
        migrations.RemoveField(
            model_name='applyjobmodel',
            name='Number_of_opening',
        ),
        migrations.RemoveField(
            model_name='applyjobmodel',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='applyjobmodel',
            name='job_title',
        ),
        migrations.AddField(
            model_name='applyjobmodel',
            name='Cover',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applyjobmodel',
            name='Expected_Salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applyjobmodel',
            name='Full_Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='applyjobmodel',
            name='Linkedin_URL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applyjobmodel',
            name='Resume',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='Media/Resume'),
        ),
        migrations.AddField(
            model_name='applyjobmodel',
            name='Work_Experience',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='applyjobmodel',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.jobmodel'),
        ),
        migrations.AddField(
            model_name='applyjobmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('interview_scheduled', 'Interview Scheduled'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='applyjobmodel',
            name='Skills',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applyjobmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
