# Generated by Django 5.1.2 on 2024-10-27 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_jobseekerprofilemodel_delete_viewersprofilemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='intermediate_skillmodel',
        ),
        migrations.DeleteModel(
            name='Skills_Model',
        ),
    ]
