# Generated by Django 5.1.2 on 2024-10-27 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_intermediate_skillmodel_delete_skills_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofilemodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewersProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
