# Generated by Django 5.1.2 on 2024-10-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_jobseekerprofilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjobmodel',
            name='Resume',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='Media/Resume'),
        ),
    ]
