# Generated by Django 5.1.2 on 2024-10-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_applyjobmodel_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjobmodel',
            name='Expected_Salary',
        ),
        migrations.RemoveField(
            model_name='applyjobmodel',
            name='Full_Name',
        ),
        migrations.RemoveField(
            model_name='applyjobmodel',
            name='Linkedin_URL',
        ),
        migrations.RemoveField(
            model_name='applyjobmodel',
            name='Work_Experience',
        ),
        migrations.RemoveField(
            model_name='applyjobmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='applyjobmodel',
            name='Apply_Image',
            field=models.ImageField(null=True, upload_to='Media/Job_Image'),
        ),
        migrations.AlterField(
            model_name='applyjobmodel',
            name='Resume',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='Media/Resume'),
        ),
    ]
