# Generated by Django 5.1.2 on 2024-11-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_applyjobmodel_expected_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjobmodel',
            name='Skills',
            field=models.CharField(choices=[('programing', 'Programing'), ('graphics_design', 'Graphics Design'), ('resarch', 'Resarch')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='Skills',
            field=models.CharField(choices=[('programing', 'Programing'), ('graphics_design', 'Graphics Design'), ('resarch', 'Resarch')], max_length=255, null=True),
        ),
    ]
